# Generated by Django 4.1.3 on 2022-11-27 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Selectyour profile picture. (.jpg)', upload_to='about', validators=[django.core.validators.FileExtensionValidator(['.jpg', '.jpeg', '.png'])])),
                ('text', models.TextField(max_length=2000)),
            ],
        ),
    ]
