# Generated by Django 4.1.3 on 2022-12-10 15:53

from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name_plural': 'Site Info'},
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pages.models.get_photos_dir)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.categories')),
            ],
        ),
    ]
